### ISSUE TITLE
Обновление до 11.3

### ISSUE THREAD

**Issue by agentik-007** [dle-modules/DLE-YandexMaps#1]
Возможно ли обновление до DLE 11.3?
После установки и переходе в админку выдает это:

> Parse error: syntax error, unexpected '[' in Z:\home\test1.ru\www\engine\modules\ymaps\admin\classes\xfields.php on line 141

**Comment by pafnuty** [comment]
@agentik-007 похоже, что у вас php <5.4

**Comment by agentik-007** [comment]
Да, извините, запускал на денвере, а не на машинке. Забыл, что там старые версии php

**Comment by pafnuty** [comment]
@agentik-007 используйте OpenServer, он ближе к реальному хостингу и в настройке проще.
