### ISSUE TITLE
yandex maps13.3

### ISSUE THREAD

**Issue by NEXTHOME** [dle-modules/DLE-YandexMaps#11]
![image](https://user-images.githubusercontent.com/28262403/72831763-f028ec80-3c9c-11ea-8a06-47609a26a6c1.png)
Прошу братан очень нужен твой модуль yandex maps для дле 13,3 пишет ошибку прошу помочь решение проблемы

**Comment by pafnuty** [comment]
@NEXTHOME опишите более детально ошибки, версию php.

**Comment by NEXTHOME** [comment]
![image](https://user-images.githubusercontent.com/28262403/72834798-fae68000-3ca2-11ea-83e9-8d77e7880eb4.png)

**Comment by NEXTHOME** [comment]
PHP Settings (v7.3.13)

**Comment by pafnuty** [comment]
Ничем не могу помочь, у вас в браузере всё в порядке. 
Ставьте лицензионную DLE, стандартный шаблон, смотрите что в логах сервера.
Так же попробуйте поставить php 5,6 например.
