### ISSUE TITLE
Не работает поиск по карте

### ISSUE THREAD

**Issue by krockki** [dle-modules/DLE-YandexMaps#12]
Привет. Установил модуль Яндекс карт для DLE 13.3. Все настроил, но не работает функция поиска объекта, ни в настройках ни при добавлении/редактировании новости. Пишет: Сервер не смог обработать запрос

**Comment by krockki** [comment]
Не могли бы вы помочь?

**Comment by pafnuty** [comment]
@krockki Яндекс изменили API, для поиска по карте нужно использовать api key.
Обновление модуля я уже сделал, осталось оформить PR и сделать новый релиз.

**Comment by krockki** [comment]
Спасибо, буду ждать
