### ISSUE TITLE
Не работают "Все метки" и метка в полной новости.

### ISSUE THREAD

**Issue by Screamer89** [dle-modules/DLE-YandexMaps#13]
Бесконечная загрузка, сама карта видна.
DLE 13.3 пробую на чистом шаблоне. В консоли только error и все. Пробовал php 7.1 и 7.3

В полной новости
Uncaught ReferenceError: $ is not defined
    at 7-stroitelstvo-novogo-korpusa-polikliniki-gbuz-rkb-im-gg-kuvatova.html:175

**Comment by pafnuty** [comment]
@Screamer89 скорее всего у вас неправильно подключены скрипты.

**Comment by Screamer89** [comment]
@pafnuty а если при добавлении новости карта отображается нормально? Или это не взаимосвязано? Сейчас попробую еще раз проверить.

**Comment by pafnuty** [comment]
@Screamer89 значит точно неправильно подключены скрипты.

**Comment by Screamer89** [comment]
@pafnuty я даже попробовал подключить все как на вашем демо сайте. Все равно не работает. Может файлам или папкам надо дать доступ на запись?

**Comment by Screamer89** [comment]
@pafnuty оказывается из-за версии MySQL не работало. В файле engine/ajax/ymaps/all.php границы слов в regexp заменил на \\\\\\\\b и все зарабало.
