### ISSUE TITLE
Интеграция с DLE Filter

### ISSUE THREAD

**Issue by Nesterovich2797** [dle-modules/DLE-YandexMaps#16]
Здравствуйте. Возможно ли интегрировать DLE Filter, чтобы на карте отображались метки отфильтрованных новостей?

**Comment by pafnuty** [comment]
@Nesterovich2797 в целом да.
Вы можете выводить из вашего модуля DLE Filter либо параметры, по которым нужно отобрать новости, либо json объект с выборкой новостей и скармливать его в JS карт. по идее даже сам модуль яндекс карт для этого не нужен, можно всё сделать через api карт.
