### ISSUE TITLE
Иконка с локацией

### ISSUE THREAD

**Issue by web5557** [dle-modules/DLE-YandexMaps#18]
После установки, загружается карта а на иконке локация надпись {short_story limit="100"}, подскажите пожалуйста как исправить.
Для вывода карты используется вот такой код {include file="engine/modules/ymaps/detail.php?template=ymaps/simple&id={news-id}"}

**Comment by pafnuty** [comment]
@web5557 Можете дать ссылку на сайт, где происходит ошибка?
