### ISSUE TITLE
Проблема получения координаты меток и добавления их

### ISSUE THREAD

**Issue by FutureHokage** [dle-modules/DLE-YandexMaps#19]
Здравствуйте. При добавлении новости на сайт, при нажатии на "Добавить метку" открывается карта, но выбрать там что-либо невозможно. Консоль выдает вот такую ошибку. 
![image](https://user-images.githubusercontent.com/70458828/91651273-1681f680-eace-11ea-9dc6-108f19e3f593.png)

**Comment by pafnuty** [comment]
Добрый день. Дайте ссылку на страницу с ошибкой

**Comment by FutureHokage** [comment]
amurpogoda.com/admin.php
admin
-----

вт, 1 сент. 2020 г., 23:17 Pavel Belousov <notifications@github.com>:

**Comment by pafnuty** [comment]
@FutureHokage У вас в настройках модуля не была задана иконка для метки по умолчанию. 
Не забудьте сменить пароль, issue на гитхабе - общедоступные страницы.

**Comment by FutureHokage** [comment]
Хорошо. Спасибо огромное. А есть ещё вопрос. Мне нужно, чтобы было два вида
меток. Вид их должен зависеть от содержимого доп.полей. больше или меньше
заданного числа. В каком файле модуля мне разумнее покопаться и попробовать
это реализовать?

вт, 1 сент. 2020 г., 23:26 Pavel Belousov <notifications@github.com>:

**Comment by pafnuty** [comment]
https://github.com/dle-modules/DLE-YandexMaps/blob/1829fa130ee2b9ed4177b05f015f3fe37dc3f273/engine/modules/ymaps/detail.php#L76
вот тут формируется стиль метки.
Я бы рекомендовал делать дополнение к модулю как отдельный плагин, тогда не придётся волноваться при обновлении.
