### ISSUE TITLE
Проблема с работой модуля)

### ISSUE THREAD

**Issue by ayzat-ziganshin** [dle-modules/DLE-YandexMaps#2]
залил все необходимое в корень.
сделал все по инструкции. Не добавляется метка, а в случае модального окна -не работают кнопки в принципе.

здесь вызов добавления метки по кнопке https://vk.cc/6SLCDZ
здесь непосредственно в самой новости https://vk.cc/6SLCNP

dle 11.3 , php5.4 , utf-8, ionCube Loader: да
доступ к админке - test test

**Comment by pafnuty** [comment]
@Kznfree логин и пароль не подходят.
