### ISSUE TITLE
Не работает модуль

### ISSUE THREAD

**Issue by calfetko** [dle-modules/DLE-YandexMaps#5]
Версия движка  DLE 11.0
Установил модуль как по инструкции, добавил возможность выбора места на карте в модальном окне в шаблоне addnews.tpl, далее выбираю место нажимаю применить, окно не сворачивается. Нажимаю сбросить, ничего не сбрасывается, нажимаю на крестик в модальном окне, оно не закрывается. проверил на вашем сайте в демо доступе, абсолютно такие же ошибки. Модальное окно не закрывается, кнопки сбросить и применить тоже не работают. 
P.S 
Браузер Chrome

**Comment by pafnuty** [comment]
@calfetko Напишите адрес сайта, где можно наблюдать описанные ошибки.

**Comment by calfetko** [comment]
Логин pafnuty
Пароль 
1nogtevoy.ru/admin.php
Также добавление новостей из админки, там вообще кнопка не появилась, хотя код подправил....
Ну а в основном вот на главной странице сайта, кнопка добавить объявление...

**Comment by pafnuty** [comment]
А при заходе в админку модуля есть какието ошибки php в логах?

**Comment by calfetko** [comment]
только что включил логирование... пока все пусто...

**Comment by calfetko** [comment]
...

**Comment by calfetko** [comment]
Ошибок так и не появилось... в какую сторону копать, модуль вообще рабочий? на тестовом сайте вашем, тоже такие же проблемы...

**Comment by pafnuty** [comment]
@calfetko только что проверил тестовый сайт, там всё ок.
Попробуйте установить чистую версию DLE, потом установить модуль.

**Comment by calfetko** [comment]
на тестовой версии, с пользовательского интерфейса, попробуйте указать метку на карте, у меня метка указывается, а карта не закрывается..

**Comment by calfetko** [comment]
и еще вопрос, реально ли вытащить улицу, дом отмеченные на карте и добавить в доп поле при добавлении новости... ?

**Comment by pafnuty** [comment]
@calfetko https://i.imgur.com/4s7iWTp.gifv 
Пожалуйста, проверьте работу модуля на чистой версии DLE с дефолтным шаблоном, убедитесь, что у вас загружается api яндекс карт (в некоторых странах оно не работает). 

Всё реально. 
Код перед вами в этом репозитории, API карт так же имеют собственную документацию и примеры. 

Вы можете склонировать репозиторий, добавить нужный функционал и отправить Pull Request что бы все могли пользоваться кодом.

**Comment by calfetko** [comment]
ок, сегодня проверю на чистой версии dle, я так понимаю линейка 11 версий поддерживается модулем...

**Comment by calfetko** [comment]
у вас какой браузер стоит? вот прямо сейчас зашел на ваш сайт: http://demomap.pafnuty.name/addnews.html, выбрал категорию 1, пытаюсь добавить метку, ввел адрес, ставлю метку, дальше нажимаю применить(ноль реакции). крести(ноль реакции), сбросить, тоже самое...

**Comment by calfetko** [comment]
https://imgur.com/8EGSYbX

**Comment by calfetko** [comment]
какая то загадка, у вас работает модуль, а у меня нет, при том на вашем тестовом сайте, с разных машин уже заходил...

**Comment by pafnuty** [comment]
@calfetko Если вы хотите обсудить ошибку на сайте с демо, пожалуйста, создайте новый тиккет, проверьте работу сайта в трёх брайзерах (любой хромобраузер актуальной версии , FF, IE11+). Укажите какие ошибки (если они есть) появляются в консоли. 
Но не стоит расчитывать на быстрое решение проблемы т.к. демосайт я уже давно не поддерживаю. 
Сам модуль поддерживается на уровне моего желания, которое есть не всегда? а это означает, что тоже не стоит расчитывать на быстрое решение экзотической проблемы, как в вашем случае :smile:.

**Comment by calfetko** [comment]
значится так, вот поставил чистую версию dle 10.0 установил ваш скрипт, вывел кнопку добавления в пользовательском интерфейсе. все как по инструкции. результат тот же. логин и пароль demo demo адреса http://aeropuffing.1nogtevoy.ru

**Comment by calfetko** [comment]
версия php какая на хостинге должна быть?
