### ISSUE TITLE
Не выводит метки DLE 12.1

### ISSUE THREAD

**Issue by VitArts** [dle-modules/DLE-YandexMaps#7]
## **Приветствую Павел.**

Покупал в свое время не одну лицензию модуля, сейчас обнаружил, что стало бесплатно, это одновременно радостно и грустно.. 

Спасибо Вам за труды и отзывчивость. 

**Нашел на Вашем сайте сообщение:**
> Приветствую. Установил ваш модуль на DLE- карта вывелась - вот почему то не подхватываются координаты.Всегда используются координаты по умолчанию. Подскажите где копать?

У меня такая же проблема, вывод карты в полной новости происходит по умолчанию из  [настроек карты](http://joxi.ru/BA0037nfJOwN7A) , вот в  [полной новости](http://joxi.ru/12MYG87SMaX7x2), а вот так уже в [редактирование новостей](http://joxi.ru/RmzxpaKh0BGd3A).

В чем может быть причина?

**Comment by pafnuty** [comment]
@VitArts возможно:
- особенности браузера (расширения, блокировщици рекламы) 
- JS ошибки на сайте
- Особенности шаблона
- Некорректная устанока модуля

**Comment by VitArts** [comment]
те исключено, что в DLE что-то поменялось?

**Comment by VitArts** [comment]
Вот [скрин какие данные выводятся в дополнительном поле и какие в js](http://joxi.ru/a2XZd6au187eJr)

**Comment by pafnuty** [comment]
@VitArts не исключено, что в DLE произошли изменения, надо проверить.

**Comment by VitArts** [comment]
Спасибо большое, очень жду решения...

**Comment by VitArts** [comment]
Паш не смотрел данную проблему? Может быть за деньги можно решить?

**Comment by VitArts** [comment]
Сделал вот такой костыль:

```
        var strJSON = '[xfvalue_cor]';
	var data = $.parseJSON(strJSON);

	var
	  lon = data.lon,
	  lat = data.lat,
	  zoom = data.zoom,
```

**Comment by pafnuty** [comment]
@VitArts В версии модуля 3.0.0 это будет исправлено.
