### ISSUE TITLE
Слетают координаты метки при изменении масштаба во время добавления новости

### ISSUE THREAD

**Issue by Colonizator1** [dle-modules/DLE-YandexMaps#8]
Добавляем метку с сайта либо через админку. Если после клика по карте для создания метки изменить масштаб - координаты метки устанавливаются по умолчанию. Гифка воспроизводящая ошибку:

![ezgif com-optimize](https://user-images.githubusercontent.com/39800054/40785258-b3f6e0f8-64f0-11e8-9cd0-a3462cc0ba2f.gif)
Для наглядности вывел поле с координатами куда пишутся данные метки.

**Comment by pafnuty** [comment]
@Colonizator1 какой браузер вы используете? 
Есть ли js ошибки в консоли?

**Comment by Colonizator1** [comment]
В консоли в админке - пусто. Браузер FF, Opera. DLE 13.0 чистая.
При добавлении через сайт в консоли: TypeError: e is null - но это как я понимаю к проблеме не относится.

**Comment by pafnuty** [comment]
@Colonizator1 а можете дать ссылку на сайт? Возможно оно косвенно затрагивает, надо проверить.

**Comment by Colonizator1** [comment]
@pafnuty Написал на почту сайт и доступ.

**Comment by never3d22** [comment]
Что было?

**Comment by Colonizator1** [comment]
@never3d22 так и не понял, не разбирался, делаю с нуля под свои задачи все.
